language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed songokudev/udagram-api-feed:v4
  - docker tag udagram-api-user songokudev/udagram-api-user:v4
  - docker tag udagram-frontend songokudev/udagram-frontend:v5
  - docker tag reverseproxy songokudev/reverseproxy:v4

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push songokudev/udagram-api-feed:v4
  - docker push songokudev/udagram-api-user:v4
  - docker push songokudev/udagram-frontend:v4
  - docker push songokudev/reverseproxy:v4
  