apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    service: frontend
spec:
  selector:
    service: frontend
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  type: LoadBalancer